/**
 * Form helpers for development/testing - auto-fill forms with valid test data.
 * Only used in local/dev environment to speed up testing workflows.
 */

export interface TestUser {
  name: string
  email: string
  password: string
  role: string
}

/** Test users generated by DatabaseSeeder */
export const testUsers: TestUser[] = [
  { name: 'Admin Principal', email: 'admin@larahealth.com', password: 'password', role: 'Admin' },
  { name: 'Operador João', email: 'operacional@larahealth.com', password: 'password', role: 'Operacional' },
  { name: 'Carlos Almeida', email: 'dr.Cardiologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Ana Beatriz Barbosa', email: 'dr.Dermatologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Rafael Costa', email: 'dr.Ortopedia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Juliana Dias', email: 'dr.Pediatria@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Fernando Fernandes', email: 'dr.Neurologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Marina Gomes', email: 'dr.Ginecologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Thiago Lima', email: 'dr.Oftalmologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Camila Martins', email: 'dr.Psiquiatria@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Eduardo Nogueira', email: 'dr.Endocrinologia@larahealth.com', password: 'password', role: 'Profissional' },
  { name: 'Patrícia Oliveira', email: 'dr.Urologia@larahealth.com', password: 'password', role: 'Profissional' },
]

/** Generate a valid test CPF (without validation, just for filling forms) */
export function generateTestCpf(): string {
  const n = (max: number) => Math.floor(Math.random() * max)
  const n9 = `${n(9)}${n(9)}${n(9)}${n(9)}${n(9)}${n(9)}${n(9)}${n(9)}${n(9)}`
  // Simple CPF-like number for testing
  return `${n9.slice(0, 3)}.${n9.slice(3, 6)}.${n9.slice(6, 9)}-${n(9)}${n(9)}`
}

/** Generate test patient registration data */
export function generateTestPatientData() {
  const firstNames = ['Maria', 'João', 'Ana', 'Carlos', 'Fernanda', 'Pedro', 'Juliana', 'Lucas', 'Patrícia', 'Rafael']
  const lastNames = ['Silva', 'Santos', 'Oliveira', 'Souza', 'Costa', 'Pereira', 'Lima', 'Almeida', 'Nascimento', 'Barbosa']

  return {
    name: `${firstNames[Math.floor(Math.random() * firstNames.length)]} ${lastNames[Math.floor(Math.random() * lastNames.length)]}`,
    email: `teste${Date.now()}@email.com`,
    password: 'password',
    password_confirmation: 'password',
    cpf: generateTestCpf(),
    birth_date: `${Math.floor(Math.random() * 50 + 1950)}-${String(Math.floor(Math.random() * 12) + 1).padStart(2, '0')}-${String(Math.floor(Math.random() * 28) + 1).padStart(2, '0')}`,
    phone: `(${String(Math.floor(Math.random() * 90) + 10)}) ${Math.floor(Math.random() * 90000 + 10000)}-${Math.floor(Math.random() * 9000 + 1000)}`,
    street: `${Math.floor(Math.random() * 5000 + 100)} Rua das Flores`,
    neighborhood: 'Centro',
    city: 'São Paulo',
    state: 'SP',
    zip_code: `${String(Math.floor(Math.random() * 90000 + 10000))}-${String(Math.floor(Math.random() * 900 + 100))}`,
    main_complaint: 'Dor de cabeça persistente há 3 dias.',
    clinical_history: 'Paciente sem comorbidades conhecidas.',
  }
}

/** Generate test unavailability period data */
export function generateTestUnavailabilityData() {
  const today = new Date()
  const startDate = new Date(today)
  startDate.setDate(today.getDate() + Math.floor(Math.random() * 30) + 10)

  const endDate = new Date(startDate)
  endDate.setDate(startDate.getDate() + Math.floor(Math.random() * 10) + 3)

  const reasons = ['Férias', 'Licença médica', 'Plantão externo', 'Congresso', 'Curso']

  return {
    start_date: startDate.toISOString().split('T')[0],
    end_date: endDate.toISOString().split('T')[0],
    reason: reasons[Math.floor(Math.random() * reasons.length)],
  }
}

/** Generate test message data */
export function generateTestMessageData() {
  const subjects = [
    'Encaminhamento de paciente',
    'Solicitação de exames',
    'Resultado de exames',
    'Confirmação de consulta',
    'Relatório de atendimento',
  ]

  const contents = [
    'Prezado(a), conforme conversamos, estou encaminhando o paciente para avaliação especializada.',
    'Solicito a realização dos exames conforme protocolo estabelecido.',
    'Segue em anexo o resultado dos exames solicitados na última consulta.',
    'Confirmo o agendamento da consulta para a data prevista.',
    'Encaminho o relatório de atendimento para análise.',
  ]

  return {
    subject: subjects[Math.floor(Math.random() * subjects.length)],
    content: contents[Math.floor(Math.random() * contents.length)],
  }
}
